apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

images:
  - name: ghcr.io/foodsphere/foodsphere-frontend/pos-app
    newName: ghcr.io/foodsphere/foodsphere-frontend/pos-app
    newTag: latest